# Default setup is given for MySQL 5.7.7 or later.
# Examples for PostgreSQL, SQLite3 and SQL Server can be found at the end.
# Line indentation must be 2 spaces (no tabs).

# Development Environment
development:
  adapter: postgresql
  database: redmine_development
  host: localhost
  username: redmine_user
  password: "your_password"
  encoding: unicode

# Test Environment
test:
  adapter: postgresql
  database: redmine_test
  host: localhost
  username: redmine_user
  password: "your_password"
  encoding: unicode

# Production Environment
production:
  adapter: postgresql
  database: redmine_production
  host: localhost
  username: redmine_user
  password: "your_password"
  encoding: unicode
  pool: 5
  timeout: 5000
