# Default setup is given for MySQL 5.7.7 or later.
# Examples for PostgreSQL, SQLite3 and SQL Server can be found at the end.
# Line indentation must be 2 spaces (no tabs).

# Development Environment
development:
  adapter: postgresql
  database: redmine_db_zaka
  host: dpg-d0ddc0muk2gs73d09au0-a
  username: redmine_db_zaka_user
  password: "Vu1JYQwDK7NxAaYjRu871UWGYlWM03Nr"
  encoding: unicode

# Test Environment
test:
  adapter: postgresql
  database: redmine_db_zaka
  host: dpg-d0ddc0muk2gs73d09au0-a
  username: redmine_db_zaka_user
  password: "Vu1JYQwDK7NxAaYjRu871UWGYlWM03Nr"
  encoding: unicode

# Production Environment
production:
  adapter: postgresql
  database: redmine_db_zaka
  host: dpg-d0ddc0muk2gs73d09au0-a
  username: redmine_db_zaka_user
  password: "Vu1JYQwDK7NxAaYjRu871UWGYlWM03Nr"
  encoding: unicode
  pool: 5
  timeout: 5000
